"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import * as api from "@/lib/api";
import type { TickConstraints } from "@/lib/api";
import type { TickPhase, TickResponse } from "@/lib/types";

export function useTick(systemId?: string, discoveryUrl?: string) {
  const [phase, setPhase] = useState<TickPhase>("idle");
  const [response, setResponse] = useState<TickResponse | null>(null);
  const [visibleNodes, setVisibleNodes] = useState(0);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const autoIntervalRef = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
      if (autoIntervalRef.current) clearInterval(autoIntervalRef.current);
    };
  }, []);

  const clearError = useCallback(() => setError(null), []);

  const reset = useCallback(() => {
    if (timerRef.current) clearInterval(timerRef.current);
    timerRef.current = null;
    setPhase("idle");
    setResponse(null);
    setVisibleNodes(0);
    setIsLoading(false);
    setError(null);
    setAutoGenerated(false);
  }, []);

  const animateTrace = useCallback(
    (resp: TickResponse, startFrom: number = 0, finalPhase?: TickPhase) => {
      const trace = resp.decision_trace;
      let count = startFrom;
      setVisibleNodes(startFrom);

      if (timerRef.current) clearInterval(timerRef.current);

      timerRef.current = setInterval(() => {
        count++;
        setVisibleNodes(count);
        if (count >= trace.length) {
          if (timerRef.current) clearInterval(timerRef.current);
          timerRef.current = null;
          setPhase(finalPhase ?? (resp.phase as TickPhase));
        }
      }, 350);
    },
    [],
  );

  const runTick = useCallback(async (constraints?: TickConstraints, isAuto?: boolean) => {
    if (timerRef.current) clearInterval(timerRef.current);
    setPhase("running");
    setResponse(null);
    setVisibleNodes(0);
    setIsLoading(true);
    setError(null);
    setAutoGenerated(!!isAuto);

    try {
      const resp = await api.runTick(systemId, discoveryUrl, constraints);
      setResponse(resp);

      if (resp.error) {
        setError(resp.error);
        setPhase("idle");
        return;
      }

      animateTrace(resp);
    } catch (e) {
      const msg = e instanceof Error ? e.message : "Analysis failed — check that the API server is running.";
      setError(msg);
      setPhase("idle");
    } finally {
      setIsLoading(false);
    }
  }, [systemId, discoveryUrl, animateTrace]);

  const approve = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const oldLen = response?.decision_trace.length ?? 0;
      const resp = await api.approvePlan();
      setResponse(resp);
      animateTrace(resp, oldLen, "dispatched");
    } catch (e) {
      setError(e instanceof Error ? e.message : "Approve failed");
    } finally {
      setIsLoading(false);
    }
  }, [response, animateTrace]);

  const reject = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const resp = await api.rejectPlan();
      setResponse(resp);
      setVisibleNodes(resp.decision_trace.length);
      setPhase("rejected");
    } catch (e) {
      setError(e instanceof Error ? e.message : "Reject failed");
    } finally {
      setIsLoading(false);
    }
  }, []);

  const setAutoInterval = useCallback((hours: number, constraints?: TickConstraints) => {
    if (autoIntervalRef.current) clearInterval(autoIntervalRef.current);
    autoIntervalRef.current = null;
    if (hours <= 0) return;
    autoIntervalRef.current = setInterval(() => {
      runTick(constraints, true);
    }, hours * 3600_000);
  }, [runTick]);

  const clearAutoInterval = useCallback(() => {
    if (autoIntervalRef.current) clearInterval(autoIntervalRef.current);
    autoIntervalRef.current = null;
  }, []);

  return {
    phase,
    response,
    visibleNodes,
    runTick,
    approve,
    reject,
    isLoading,
    error,
    clearError,
    reset,
    autoGenerated,
    setAutoInterval,
    clearAutoInterval,
  };
}
