"use client";

import dynamic from "next/dynamic";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ChevronDown, ChevronRight } from "lucide-react";
import Header from "@/components/Header";
import JourneyBar from "@/components/JourneyBar";
import KpiStrip from "@/components/KpiStrip";
import ControlsBar from "@/components/ControlsBar";
import AgentTrace from "@/components/AgentTrace";
import PlanPanel from "@/components/PlanPanel";
import StationRiskChart from "@/components/StationRiskChart";
import HistoryPanel from "@/components/HistoryPanel";
import { useTheme } from "@/hooks/useTheme";
import { useTick } from "@/hooks/useTick";
import { useGbfs } from "@/hooks/useGbfs";
import { useSystem } from "@/hooks/useSystem";
import { useWindowSize } from "@/hooks/useWindowSize";
import type { TickConstraints } from "@/lib/api";
const MapView = dynamic(() => import("@/components/MapView"), { ssr: false });

const NODE_TO_STEP: Record<string, number> = {
  ingest: 1,
  forecast: 2,
  assess_imbalance: 3,
  plan: 4,
  evaluate_plan: 4,
  relax_constraints: 4,
  explain: 5,
  human_approval: 6,
  dispatch: 7,
};

const TRACE_STORAGE = "fleet-rebalancer-trace-open";
const RISK_STORAGE = "fleet-rebalancer-risk-open";

function useCollapsible(storageKey: string, defaultOpen = false) {
  const [open, setOpen] = useState(defaultOpen);
  useEffect(() => {
    try {
      const v = localStorage.getItem(storageKey);
      if (v !== null) setOpen(v === "1");
    } catch {}
  }, [storageKey]);
  const toggle = useCallback(() => {
    setOpen((prev) => {
      const next = !prev;
      try { localStorage.setItem(storageKey, next ? "1" : "0"); } catch {}
      return next;
    });
  }, [storageKey]);
  return { open, toggle };
}

export default function Home() {
  const { theme, setTheme } = useTheme();
  const {
    systems, selected: selectedSystem, setSelected: setSelectedSystem,
    loading: systemsLoading, validationProgress, validationTotal,
    regionFilter, setRegionFilter, showAllTypes, setShowAllTypes,
  } = useSystem();
  const gbfs = useGbfs(selectedSystem.autoDiscoveryUrl);
  const {
    phase, response, visibleNodes, runTick, approve, reject,
    isLoading, error: tickError, clearError, reset: resetTick,
    autoGenerated, setAutoInterval, clearAutoInterval,
  } = useTick(selectedSystem.systemId, selectedSystem.autoDiscoveryUrl);

  const [constraints, setConstraints] = useState<TickConstraints>({
    van_count: 3,
    van_capacity: 25,
    shift_budget_min: 120,
  });

  const prevSystemIdRef = useRef(selectedSystem.systemId);
  useEffect(() => {
    if (prevSystemIdRef.current !== selectedSystem.systemId) {
      prevSystemIdRef.current = selectedSystem.systemId;
      resetTick();
    }
  }, [selectedSystem.systemId, resetTick]);

  useEffect(() => {
    return () => clearAutoInterval();
  }, [clearAutoInterval]);

  const handleAutoChange = useCallback(
    (hours: number) => {
      if (hours <= 0) {
        clearAutoInterval();
      } else {
        setAutoInterval(hours, constraints);
      }
    },
    [setAutoInterval, clearAutoInterval, constraints],
  );

  const handleRunTick = useCallback(() => {
    runTick(constraints);
  }, [runTick, constraints]);

  const { width } = useWindowSize();
  const isCompact = width < 1024;

  const trace = response?.decision_trace ?? [];
  const visibleTrace = trace.slice(0, visibleNodes);
  const completedStepSet = new Set<number>();
  let activeStep = 0;
  for (const node of visibleTrace) {
    const step = NODE_TO_STEP[node];
    if (step) completedStepSet.add(step);
  }
  if (phase === "idle" && response !== null && !response.trigger) {
    completedStepSet.add(1);
    completedStepSet.add(2);
    completedStepSet.add(3);
    activeStep = 0;
  } else if (phase === "approval") { completedStepSet.delete(6); activeStep = 6; }
  else if (phase === "running") {
    const maxCompleted = Math.max(...completedStepSet, 0);
    activeStep = maxCompleted < 7 ? maxCompleted + 1 : 0;
  }
  const completedSteps = [...completedStepSet];
  const showRoutes = (phase === "approval" || phase === "dispatched") && response?.plan;

  const kpiHealth = useMemo(() => {
    if (response?.kpi.health != null) return response.kpi.health;
    return gbfs.health;
  }, [response, gbfs.health]);

  const kpiStarving = useMemo(() => {
    if (response?.kpi.starving != null && response.kpi.starving > 0) return response.kpi.starving;
    return gbfs.counts.starving;
  }, [response, gbfs.counts.starving]);

  const kpiSaturated = useMemo(() => {
    if (response?.kpi.saturated != null && response.kpi.saturated > 0) return response.kpi.saturated;
    return gbfs.counts.saturated;
  }, [response, gbfs.counts.saturated]);

  const tracePanel = useCollapsible(TRACE_STORAGE);
  const riskPanel = useCollapsible(RISK_STORAGE);

  const traceSummary = response
    ? `${trace.length} nodes · ${response.llm_calls} LLM call${response.llm_calls !== 1 ? "s" : ""}`
    : "no data";
  const riskCount = gbfs.stations.filter((s) => s.risk !== "healthy").length;
  const riskSummary = gbfs.stations.length > 0
    ? `${riskCount} station${riskCount !== 1 ? "s" : ""} flagged`
    : "no data";

  return (
    <div style={{ height: "100vh", display: "flex", flexDirection: "column", overflow: "hidden", background: "var(--bg)" }}>

      <Header
        theme={theme}
        onThemeChange={setTheme}
        onRunTick={handleRunTick}
        phase={phase}
        systems={systems}
        selectedSystem={selectedSystem}
        onSystemChange={setSelectedSystem}
        systemsLoading={systemsLoading}
        forecastMethod={response?.forecast_method}
        regionFilter={regionFilter}
        onRegionChange={setRegionFilter}
        validationProgress={validationProgress}
        validationTotal={validationTotal}
        showAllTypes={showAllTypes}
        onShowAllTypesChange={setShowAllTypes}
      />
      <ControlsBar
        constraints={constraints}
        onConstraintsChange={setConstraints}
        onAutoChange={handleAutoChange}
      />
      <JourneyBar phase={phase} activeStep={activeStep} completedSteps={completedSteps} />

      <div style={{ flex: 1, minHeight: 0, display: "flex", flexDirection: "column", padding: "8px 20px", gap: 8, overflow: "auto" }}>

        {/* KPI strip */}
        <div style={{ flexShrink: 0 }}>
          <KpiStrip
            health={kpiHealth}
            starving={kpiStarving}
            saturated={kpiSaturated}
            totalStations={gbfs.stations.length}
            lastUpdated={gbfs.lastUpdated}
          />
        </div>

        {/* Map + plan panel */}
        <div
          style={
            isCompact
              ? { display: "flex", flexDirection: "column", gap: 12, flexShrink: 0 }
              : { flex: 1, minHeight: 400, display: "grid", gridTemplateColumns: "1fr 420px", gap: 12 }
          }
        >
          <div style={isCompact ? { height: 400, borderRadius: 12, overflow: "hidden" } : { height: "100%", minHeight: 0, borderRadius: 12, overflow: "hidden" }}>
            <MapView
              stations={gbfs.stations}
              counts={gbfs.counts}
              loading={gbfs.loading}
              error={gbfs.error}
              onRetry={gbfs.retry}
              routes={showRoutes ? response!.plan : undefined}
              theme={theme}
              systemKey={selectedSystem.systemId}
            />
          </div>
          <div style={isCompact ? { minHeight: 300, overflow: "hidden" } : { height: "100%", minHeight: 0, overflow: "hidden" }}>
            <PlanPanel
              phase={phase}
              response={response}
              onApprove={approve}
              onReject={reject}
              isLoading={isLoading}
              error={tickError}
              onDismissError={clearError}
              systemName={selectedSystem.name}
              stationCount={gbfs.stations.length}
              autoGenerated={autoGenerated}
            />
          </div>
        </div>

        {/* Bottom row: collapsible trace + risk */}
        <div style={{ flexShrink: 0, display: "flex", flexDirection: "column", gap: 8, paddingBottom: 8 }}>
          <div
            style={
              isCompact
                ? { display: "flex", flexDirection: "column", gap: 8 }
                : { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }
            }
          >
            {/* Decision Trace accordion */}
            <div className="glass rounded-xl" style={{ overflow: "hidden" }}>
              <button
                onClick={tracePanel.toggle}
                className="flex items-center gap-2 w-full"
                style={{ height: 36, padding: "0 12px", background: "none", border: "none", cursor: "pointer", color: "var(--text2)" }}
              >
                {tracePanel.open ? <ChevronDown size={12} /> : <ChevronRight size={12} />}
                <span style={{ fontSize: 11, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.08em" }}>
                  Decision Trace
                </span>
                {!tracePanel.open && (
                  <span style={{ fontSize: 10, color: "var(--text3)", fontFamily: "var(--font-mono)" }}>
                    · {traceSummary}
                  </span>
                )}
              </button>
              <div style={{ maxHeight: tracePanel.open ? 260 : 0, overflow: "hidden", transition: "max-height 0.3s ease" }}>
                <div style={{ height: 240, padding: "0 0 8px" }}>
                  <AgentTrace phase={phase} response={response} visibleNodes={visibleNodes} embedded />
                </div>
              </div>
            </div>

            {/* At-Risk Stations accordion */}
            <div className="glass rounded-xl" style={{ overflow: "hidden" }}>
              <button
                onClick={riskPanel.toggle}
                className="flex items-center gap-2 w-full"
                style={{ height: 36, padding: "0 12px", background: "none", border: "none", cursor: "pointer", color: "var(--text2)" }}
              >
                {riskPanel.open ? <ChevronDown size={12} /> : <ChevronRight size={12} />}
                <span style={{ fontSize: 11, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.08em" }}>
                  At-Risk Stations
                </span>
                {!riskPanel.open && (
                  <span style={{ fontSize: 10, color: "var(--text3)", fontFamily: "var(--font-mono)" }}>
                    · {riskSummary}
                  </span>
                )}
              </button>
              <div style={{ maxHeight: riskPanel.open ? 260 : 0, overflow: "hidden", transition: "max-height 0.3s ease" }}>
                <div style={{ height: 240, padding: "0 0 8px" }}>
                  <StationRiskChart stations={gbfs.stations} embedded />
                </div>
              </div>
            </div>
          </div>

          {/* History panel */}
          <HistoryPanel />
        </div>

      </div>
    </div>
  );
}
