"use client";

import { useState } from "react";
import {
  AlertCircle,
  ArrowDown,
  ArrowUp,
  Check,
  ChevronDown,
  ChevronUp,
  Info,
  Radio,
  Truck,
  X,
  Zap,
} from "lucide-react";
import type { Route, TickPhase, TickResponse } from "@/lib/types";

interface PlanPanelProps {
  phase: TickPhase;
  response: TickResponse | null;
  onApprove: () => void;
  onReject: () => void;
  isLoading: boolean;
  error: string | null;
  onDismissError?: () => void;
  systemName?: string;
  stationCount?: number;
  autoGenerated?: boolean;
}

function ErrorBanner({ message, onDismiss }: { message: string; onDismiss?: () => void }) {
  return (
    <div
      style={{
        display: "flex",
        alignItems: "flex-start",
        gap: 8,
        padding: "8px 12px",
        borderRadius: 8,
        background: "var(--red-d)",
        border: "1px solid var(--red)",
        marginBottom: 8,
      }}
    >
      <AlertCircle size={14} style={{ color: "var(--red)", flexShrink: 0, marginTop: 1 }} />
      <span style={{ fontSize: 12, color: "var(--red)", flex: 1 }}>{message}</span>
      {onDismiss && (
        <button
          onClick={onDismiss}
          style={{ background: "none", border: "none", cursor: "pointer", padding: 0 }}
        >
          <X size={12} style={{ color: "var(--red)" }} />
        </button>
      )}
    </div>
  );
}

function ImpactGrid({ response }: { response: TickResponse }) {
  const impact = response.projected_impact;
  if (!impact) return null;

  const rows = [
    {
      label: "Health",
      before: `${(impact.do_nothing_health * 100).toFixed(1)}%`,
      after: `${(impact.planned_health * 100).toFixed(1)}%`,
      delta: `${impact.health_improvement >= 0 ? "+" : ""}${(impact.health_improvement * 100).toFixed(1)}%`,
      positive: impact.health_improvement > 0,
    },
    {
      label: "Starving",
      before: String(impact.do_nothing_starving),
      after: String(impact.planned_starving),
      delta: String(impact.planned_starving - impact.do_nothing_starving),
      positive: impact.planned_starving < impact.do_nothing_starving,
    },
    {
      label: "Saturated",
      before: String(impact.do_nothing_saturated),
      after: String(impact.planned_saturated),
      delta: String(impact.planned_saturated - impact.do_nothing_saturated),
      positive: impact.planned_saturated < impact.do_nothing_saturated,
    },
    {
      label: "Bikes moved",
      before: "—",
      after: String(impact.bikes_moved),
      delta: "",
      positive: true,
    },
  ];

  return (
    <div className="mb-3">
      <div
        style={{
          fontSize: 11, fontWeight: 600, textTransform: "uppercase",
          letterSpacing: "0.08em", color: "var(--text2)", marginBottom: 8,
        }}
      >
        Impact Assessment
      </div>
      <div className="glass2 rounded-lg overflow-hidden" style={{ fontSize: 12 }}>
        <div className="grid grid-cols-4 gap-0" style={{ borderBottom: "1px solid var(--border)" }}>
          <div className="px-3 py-1.5" />
          <div className="px-3 py-1.5 text-center" style={{ color: "var(--text3)", fontWeight: 500 }}>Before</div>
          <div className="px-3 py-1.5 text-center" style={{ color: "var(--text3)", fontWeight: 500 }}>After</div>
          <div className="px-3 py-1.5 text-center" style={{ color: "var(--text3)", fontWeight: 500 }}>&Delta;</div>
        </div>
        {rows.map((row) => (
          <div key={row.label} className="grid grid-cols-4 gap-0" style={{ borderBottom: "1px solid var(--border)" }}>
            <div className="px-3 py-1.5" style={{ color: "var(--text2)", fontWeight: 500 }}>{row.label}</div>
            <div className="px-3 py-1.5 text-center" style={{ fontFamily: "var(--font-mono)", color: "var(--text)" }}>{row.before}</div>
            <div className="px-3 py-1.5 text-center" style={{ fontFamily: "var(--font-mono)", color: "var(--text)" }}>{row.after}</div>
            <div className="px-3 py-1.5 text-center" style={{ fontFamily: "var(--font-mono)", color: row.delta ? (row.positive ? "var(--green)" : "var(--red)") : "var(--text3)" }}>
              {row.delta}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

const COLLAPSED_STOPS = 5;

function RouteCard({ route, index }: { route: Route; index: number }) {
  const [expanded, setExpanded] = useState(false);
  const colors = ["#f59e0b", "#a78bfa", "#60a5fa", "#22c55e"];
  const color = colors[index % colors.length];
  const needsCollapse = route.stops.length > COLLAPSED_STOPS;
  const visibleStops = expanded ? route.stops : route.stops.slice(0, COLLAPSED_STOPS);

  return (
    <div className="glass2 rounded-lg p-3 mb-2">
      <div className="flex items-center gap-2 mb-2">
        <Truck size={14} color={color} />
        <span style={{ fontFamily: "var(--font-mono)", fontSize: 12, fontWeight: 600, color: "var(--text)" }}>
          Van {route.van_id + 1}
        </span>
        <span style={{ fontFamily: "var(--font-mono)", fontSize: 11, color: "var(--text3)" }}>
          {route.distance_km} km &middot; {Math.round(route.duration_min)} min
        </span>
      </div>
      <div className="flex flex-col gap-1">
        {visibleStops.map((stop, i) => (
          <div key={i} className="flex items-center gap-2">
            {stop.action === "pickup" ? <ArrowUp size={12} color="var(--red)" /> : <ArrowDown size={12} color="var(--green)" />}
            <span style={{ fontFamily: "var(--font-mono)", fontSize: 11, color: stop.action === "pickup" ? "var(--red)" : "var(--green)", fontWeight: 600, width: 36 }}>
              {stop.action === "pickup" ? "PICK" : "DROP"}
            </span>
            <span style={{ fontFamily: "var(--font-mono)", fontSize: 11, color: "var(--text2)", width: 20 }}>{stop.quantity}</span>
            <span className="truncate" style={{ fontSize: 11, color: "var(--text2)" }}>@ {stop.name}</span>
          </div>
        ))}
      </div>
      {needsCollapse && (
        <button
          onClick={() => setExpanded(!expanded)}
          className="flex items-center gap-1 mt-1.5 w-full justify-center"
          style={{ fontSize: 11, color: "var(--blue)", fontFamily: "var(--font-mono)", fontWeight: 500, background: "none", border: "none", cursor: "pointer", padding: "2px 0" }}
        >
          {expanded ? <>Collapse <ChevronUp size={12} /></> : <>Show all {route.stops.length} stops <ChevronDown size={12} /></>}
        </button>
      )}
      <div className="mt-2 pt-2 flex items-center gap-3" style={{ borderTop: "1px solid var(--border)", fontSize: 11, color: "var(--text3)", fontFamily: "var(--font-mono)" }}>
        <span>{route.total_pickups} pickups</span>
        <span>{route.total_dropoffs} dropoffs</span>
      </div>
    </div>
  );
}

function Recommendation({ response }: { response: TickResponse }) {
  const impact = response.projected_impact;
  if (!impact) return null;

  const vanCount = response.plan.length;
  const bikesTotal = impact.bikes_moved;
  const healthBefore = (impact.do_nothing_health * 100).toFixed(1);
  const healthAfter = (impact.planned_health * 100).toFixed(1);
  const delta = (impact.health_improvement * 100).toFixed(1);
  const fewerStarving = impact.do_nothing_starving - impact.planned_starving;

  return (
    <div className="glass2 rounded-lg p-3 mb-3" style={{ borderLeft: "3px solid var(--blue)" }}>
      <div style={{ fontSize: 12, color: "var(--text)", lineHeight: 1.6 }}>
        <span style={{ fontWeight: 600 }}>Agent recommends:</span>{" "}
        dispatch {vanCount} van{vanCount !== 1 ? "s" : ""} to move {bikesTotal} bikes.
        Projected outcome: network health {healthBefore}% &rarr; {healthAfter}% (+{delta}%),{" "}
        {fewerStarving} fewer starving station{fewerStarving !== 1 ? "s" : ""}.
      </div>
    </div>
  );
}

export default function PlanPanel({
  phase,
  response,
  onApprove,
  onReject,
  isLoading,
  error,
  onDismissError,
  systemName,
  stationCount,
  autoGenerated,
}: PlanPanelProps) {
  if (phase === "idle" && response?.idle_reason) {
    return (
      <div className="glass rounded-xl flex items-center justify-center p-6" style={{ height: "100%" }}>
        <div style={{ textAlign: "center", maxWidth: 320 }}>
          {error && <ErrorBanner message={error} onDismiss={onDismissError} />}
          <div className="flex justify-center mb-3">
            <div
              className="flex items-center justify-center rounded-full"
              style={{ width: 40, height: 40, background: "var(--blue-d)", border: "1px solid var(--blue)" }}
            >
              <Info size={18} style={{ color: "var(--blue)" }} />
            </div>
          </div>
          <div style={{ fontSize: 14, fontWeight: 600, color: "var(--text)", marginBottom: 6 }}>
            No action needed
          </div>
          <div
            className="glass2 rounded-lg p-3 mb-3"
            style={{ borderLeft: "3px solid var(--blue)", fontSize: 12, color: "var(--text2)", lineHeight: 1.6, textAlign: "left" }}
          >
            {response.idle_reason}
          </div>
          <div style={{ fontSize: 11, color: "var(--text3)", fontFamily: "var(--font-mono)" }}>
            {response.stations_count.toLocaleString()} stations analyzed · {response.llm_calls} LLM calls
          </div>
          {systemName && (
            <div style={{ fontSize: 11, color: "var(--text3)", marginTop: 4, fontFamily: "var(--font-mono)" }}>
              System: {systemName}
            </div>
          )}
        </div>
      </div>
    );
  }

  if (phase === "idle" || !response) {
    return (
      <div className="glass rounded-xl flex items-center justify-center p-6" style={{ height: "100%" }}>
        <div style={{ textAlign: "center", maxWidth: 280 }}>
          {error && <ErrorBanner message={error} onDismiss={onDismissError} />}
          <div className="flex justify-center mb-3">
            <div
              className="flex items-center justify-center rounded-full"
              style={{ width: 40, height: 40, background: "var(--green-d)", border: "1px solid var(--green)" }}
            >
              <Radio size={18} style={{ color: "var(--green)" }} />
            </div>
          </div>
          <div style={{ fontSize: 14, fontWeight: 600, color: "var(--text)", marginBottom: 6 }}>
            Network monitor active
          </div>
          <div style={{ fontSize: 12, color: "var(--text2)", lineHeight: 1.6 }}>
            Live station data is loaded{stationCount ? ` (${stationCount.toLocaleString()} stations)` : ""}.
            Press <span style={{ fontWeight: 600 }}>Run Analysis</span> to forecast demand,
            plan van routes, and generate a repositioning recommendation.
          </div>
          {systemName && (
            <div style={{ fontSize: 11, color: "var(--text3)", marginTop: 8, fontFamily: "var(--font-mono)" }}>
              System: {systemName}
            </div>
          )}
        </div>
      </div>
    );
  }

  if (phase === "running") {
    return (
      <div className="glass rounded-xl flex items-center justify-center" style={{ height: "100%", color: "var(--text2)" }}>
        <div className="flex flex-col items-center gap-3">
          <div
            className="animate-spin rounded-full"
            style={{ width: 32, height: 32, border: "3px solid var(--border2)", borderTopColor: "var(--blue)" }}
          />
          <span style={{ fontFamily: "var(--font-mono)", fontSize: 13 }}>Analyzing network...</span>
        </div>
      </div>
    );
  }

  if (phase === "dispatched") {
    return (
      <div className="glass rounded-xl p-4 flex flex-col" style={{ height: "100%" }}>
        <div className="glass2 rounded-lg p-4 mb-3 text-center" style={{ background: "var(--green-d)", border: "1px solid var(--green)" }}>
          <div className="flex justify-center mb-2"><Check size={24} color="var(--green)" /></div>
          <div style={{ fontSize: 14, fontWeight: 600, color: "var(--green)" }}>Plan Dispatched</div>
          <div style={{ fontSize: 12, color: "var(--text2)", marginTop: 4 }}>
            {response.llm_calls} LLM call{response.llm_calls !== 1 ? "s" : ""}
            {response.replan_count > 0 && ` · ${response.replan_count} replan${response.replan_count !== 1 ? "s" : ""}`}
          </div>
        </div>
        <ImpactGrid response={response} />
      </div>
    );
  }

  if (phase === "rejected") {
    return (
      <div className="glass rounded-xl p-4 flex items-center justify-center" style={{ height: "100%" }}>
        <div className="text-center">
          <div className="flex justify-center mb-2"><X size={24} color="var(--red)" /></div>
          <div style={{ fontSize: 14, fontWeight: 600, color: "var(--red)" }}>Plan Rejected</div>
          <div style={{ fontSize: 12, color: "var(--text2)", marginTop: 4 }}>Plan was rejected by operator</div>
        </div>
      </div>
    );
  }

  // phase === "approval"
  return (
    <div className="glass rounded-xl flex flex-col" style={{ height: "100%" }}>
      <div className="flex-1 overflow-y-auto p-4">
        {error && <ErrorBanner message={error} onDismiss={onDismissError} />}
        {autoGenerated && (
          <div
            className="flex items-center gap-1.5 rounded-full px-2.5 py-1 mb-2"
            style={{ display: "inline-flex", fontSize: 10, fontWeight: 600, background: "var(--blue-d)", color: "var(--blue)", border: "1px solid var(--blue)" }}
          >
            🤖 Auto-generated
          </div>
        )}
        <ImpactGrid response={response} />

        {response.work_orders && (
          <div className="mb-3">
            <div className="flex items-center gap-2 mb-2">
              <span style={{ fontSize: 11, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.08em", color: "var(--text2)" }}>
                Work Order
              </span>
              <span
                className="flex items-center gap-1 rounded-full px-2 py-0.5"
                style={{ background: "var(--purple-d)", border: "1px solid var(--purple)", fontSize: 10, color: "var(--purple)" }}
              >
                <Zap size={10} />LLM
              </span>
            </div>
            <div
              className="glass2 rounded-lg p-3"
              style={{ fontSize: 12, color: "var(--text2)", lineHeight: 1.6, whiteSpace: "pre-wrap", fontFamily: "var(--font-mono)", maxHeight: 120, overflowY: "auto" }}
            >
              {response.work_orders}
            </div>
          </div>
        )}

        <div style={{ fontSize: 11, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.08em", color: "var(--text2)", marginBottom: 8 }}>
          Routes
        </div>
        {response.plan.map((route, i) => (
          <RouteCard key={route.van_id} route={route} index={i} />
        ))}
      </div>

      <div className="shrink-0 p-4" style={{ borderTop: "1px solid var(--border)" }}>
        <Recommendation response={response} />
        <div className="flex items-center gap-2">
          <button onClick={onApprove} disabled={isLoading} className="gradient-btn flex-1 flex items-center justify-center gap-2 rounded-lg py-2.5" style={{ fontSize: 13 }}>
            <Check size={16} />Approve
          </button>
          <button
            onClick={onReject}
            disabled={isLoading}
            className="flex-1 flex items-center justify-center gap-2 rounded-lg py-2.5 font-semibold"
            style={{ fontSize: 13, background: "var(--red-d)", color: "var(--red)", border: "1px solid var(--red)" }}
          >
            <X size={16} />Reject
          </button>
        </div>
      </div>
    </div>
  );
}
